project:
  type: website
  output-dir: docs

website:
  title: "Kanthanawit Js"
  description: "A personal blog on the exploration of open data and other adventures."
  favicon: images/pi.png
  site-url: "https://kanthjs.github.io/9March19XX"
  google-analytics: "G-WY647CK1PJ"


  navbar:
    logo: images/pi.png
    logo-alt: "It's Pi"
    title: อาร์ ไร ไม่ รู้
    subtitle: "The journey of Pi"

    right:
      - text: "บล๊อก"
        href: posts.qmd

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
    css: scss/styles.css
    highlight-style: gruvbox
    mainfont: "K2D"
    monofont: "Fira Code"
    df-print: kable
    code-copy: true
    code-overflow: wrap
    toc: false
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center

editor: visual
freeze: auto