---
format: html
---

ใครที่เปิดมาเจอ แสดงว่า กำลังสนใจหรืออยากรู้เกี่ยวกับ Quarto และหวังว่าคุณจะได้ประโยชน์ เกี่ยวกับมันไม่มากก็น้อย ผมเองก็เพิ่งจะเริ่มใช้มัน ทำหลายอย่างด้วยกัน อย่างเช่น เวปบล๊อกนี้ และ Ebook อีกด้วย

บทความนี้แปลมาจากบทความที่เขียนโดย [Sam clicks](https://ucsb-meds.github.io/creating-quarto-websites/) อธิบาย Quarto ซึ่งเป็นเครื่องมืออันนึง workflow สำหรับสร้างเวปไซท์ และสร้างเวปไซท์ ได้อย่างละเอียด บทความนี้ นอกจากแปลแล้ว จะอธิบายตามความเข้าใจจากการทำตามจริง

บทความที่ชวนอ่านเพิ่มเติม เพื่อให้เข้าใจมากขึ้น

\- [Posit](https://posit.co/)'s incredible

\- [Quarto documentation](https://quarto.org/)

\- [Customizing Quarto Websites using Sass & CSS](https://ucsb-meds.github.io/customizing-quarto-websites/#/title-slide)

\- [Adding a blog to your existing Quarto website](https://samanthacsik.github.io/talks_workshops/2022-10-24-quarto-blogs/).

เนื้อหาในบทความนี้ จะพบกับ callout boxes ซึ่งจะให้ข้อมูลเพิ่เติมหรือเกร็ดเล็ก เกล็ดน้อย

::: {.callout-note collapse="true"}
## Note (collapsed by default to minimize scrolling; click to expand)

This is a **note**, often providing additional context, clarification, resources, etc.
:::

::: callout-tip
This is a **tip**, with suggested workflows, organizational tips, additional tools, etc.
:::

::: callout-important
This is **important text** -- be sure to read these carefully as to not miss any important steps!
:::
